//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyanNickMasteryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeLevel
    {
        public GradeLevel()
        {
            this.LmsUsers = new HashSet<LmsUser>();
        }
    
        public byte GradeLevelId { get; set; }
        public string GradeLevelName { get; set; }
    
        public virtual ICollection<LmsUser> LmsUsers { get; set; }
    }
}
