//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyanNickMasteryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LmsUser
    {
        public LmsUser()
        {
            this.Courses = new HashSet<Course>();
            this.Rosters = new HashSet<Roster>();
            this.LmsUser1 = new HashSet<LmsUser>();
            this.LmsUsers = new HashSet<LmsUser>();
        }
    
        public int UserId { get; set; }
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string SuggestedRole { get; set; }
        public Nullable<byte> GradeLevelId { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual GradeLevel GradeLevel { get; set; }
        public virtual ICollection<Roster> Rosters { get; set; }
        public virtual ICollection<LmsUser> LmsUser1 { get; set; }
        public virtual ICollection<LmsUser> LmsUsers { get; set; }
    }
}
