//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyanNickMasteryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterAssignment
    {
        public int RosterAssignmentId { get; set; }
        public int RosterId { get; set; }
        public int AssignmentId { get; set; }
        public Nullable<decimal> PointsEarned { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Grade { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Roster Roster { get; set; }
    }
}
